### ISSUE TITLE
.local mDNS domain is incompatible with .local resolved as conventional non-Zeroconf DNS by some ISPs

### ISSUE THREAD

**Issue by ringe** [davesteele/comitup#3]
My Ubuntu install tells me the Avahi service is disabled as soon as I connect to the comitup hotspot, complaining it is a .local domain.

**Comment by davesteele** [comment]
Zeroconf/Avahi/Bonjour client support is not complete across clients (except for Apple, who originated the technology). Google says this about Ubuntu:

https://askubuntu.com/questions/339702/network-service-discovery-disabled-what-does-this-mean-for-me
http://smallbusiness.chron.com/resolving-local-ubuntu-38861.html

Note that the hotspot IP addess is always 10.42.0.1, and that a [Zeroconf Browser](https://apps.ubuntu.com/cat/applications/precise/avahi-discover/) browser can always be used to find the IP address when connected to another access point.

**Comment by jonassmedegaard** [comment]
I believe the subject of this issue is not linux being incompatible with Zeroconf, but instead - as is also tracked in [the bugreport](https://bugs.launchpad.net/ubuntu/+source/avahi/+bug/327362) linked in a comment to the askubuntu question linked above - that mDNS is incompatible with DNS-resolvable .local top-level domain.

Zeroconf is multiple things, one of them being multicast DNS resolving, which occupies the .local domain and uses it solely for Link-Local address resolving.
Some internet providers wrongly resolve queries for .local domains.  They shouldn't. That is a bug in the offerings of those ISPs, and a workaround is to use different DNS resolvers - e.g. the famous Google 8.8.8.8 resolver or the newer faster 1.1.1.1 resolver.

Please consider renaming this issue to e.g. ".local mDNS domain is incompatible with .local resolved as conventional non-Zeroconf DNS by some ISPs"

**Comment by davesteele** [comment]
The upstream bug has a [mitigation](https://github.com/lathiat/nss-mdns#etcmdnsallow), for the case where your ISP insists on resolving .local.

**Comment by davesteele** [comment]
The upstream bug has a [mitigation](https://github.com/lathiat/nss-mdns#etcmdnsallow), for the case where your ISP insists on resolving .local.
